romain_memoire_home:
    path:     /home
    defaults: { _controller: RomainMemoireBundle:Home:Home }

romain_memoire_homepage:
    path:     /
    defaults: { _controller: RomainMemoireBundle:Home:Home }

romain_memoire_show:
    path:     /show
    defaults: { _controller: RomainMemoireBundle:Show:show }

romain_memoire_edit:
    path:     /edit
    defaults: { _controller: RomainMemoireBundle:Edit:edit }

romain_memoire_edition:
    path:     /edition
    defaults: { _controller: RomainMemoireBundle:Edition:edition }

romain_memoire_admin:
    path:     /admin
    defaults: { _controller: RomainMemoireBundle:Admin:admin }

romain_memoire_admin_add:
    path:     /admin/add
    defaults: { _controller: RomainMemoireBundle:Admin:add }