<?php

namespace Romain\MemoireBundle\Repository;

/**
 * MemoireDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemoireDoctrineRepository extends \Doctrine\ORM\EntityRepository
{
}
